name: IR
dependencies:
  - numpy 
  - pandas
  - plotly
  - notebook
  - dash 
  - matplotlib
  - seaborn
  - pandas
  - pip
  - pip:
    - python-graphblas
    - networkx
    - torch
    - transformers
    - sentence-transformers
    - accelerate
    - fastapi[standard]
    - scipy


    